theme: jekyll-theme-hacker

######################################
# 网站
# 网站标题
title: Aries Website
# 网站副标题
subtitle: Personal Site
# 网站描述
description: 1669-JOSN Source
# 您的名字
author: Aries
# 网站使用的语言。对于简体中文用户来说，使用不同的主题可能需要设置成不同的值，请参考你的主题的文档自行设置，常见的有 zh-Hans和 zh-CN。
language: zh-CN
# 网站时区。Hexo 默认使用您电脑的时区。请参考 时区列表 进行设置，如 America/New_York, Japan, 和 UTC 。一般的，对于中国大陆地区可以使用 Asia/Shanghai。
timezone: Asia/Shanghai
